import type { NextPage } from 'next';
import Head from 'next/head';
import Marquee from 'react-fast-marquee';
import Hero from '../components/Hero';

const Home: NextPage = () => {
  return (
    <div className='relative'>
      <Head>
        <title>Ingenious Hackathon 20233</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='rotate-[0deg] fixed right-0 top-0'>
        <Marquee
          className='font-aurebesh opacity-[.15] text-9xl text-white'
          gradient={false}
          speed={10}
        >
          Ingenious Hackathon Ingenious Hackathon Ingenious Hackathon Ingenious
          Hackathon Ingenious Hackathon Ingenious Hackathon Ingenious Hackathon
          Ingenious Hackathon Ingenious Hackathon Ingenious Hackathon
        </Marquee>
      </div>
      <main className='text-white h-full w-screen flex flex-col items-center justify-center px-10'>
        <Hero />
        {/* <h1 className='h-screen'>s</h1> */}
        {/* <h1 className='h-screen'>s</h1>
        <h1 className='h-screen'>s</h1>
        <h1 className='h-screen'>s</h1> */}
      </main>
    </div>
  );
};

export default Home;
