import type { NextPage } from 'next'
import Head from 'next/head'
import Hero from '../components/Hero'

const Home: NextPage = () => {
    return (
        <div className="relative">
            <Head>
                <title>Ingenious Hackathon 20233</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="fixed top-0 font-aurebesh opacity-[.15] text-9xl text-white marquee">
                IngeniousHackathon
            </div>
            <main className="text-white h-full w-screen flex flex-col items-center justify-center px-10 mt-16">
                <Hero />
            </main>
        </div>
    )
}

export default Home
